"use client";
import { FormEvent, useEffect, useState } from "react";
import { Bot, CheckCircle2, KeyRound, LockKeyhole, Trash2 } from "lucide-react";
import { deskFetch } from "@/lib/api";

type Provider="alpaca"|"openrouter"; type Status={provider:string;configured:boolean;enabled:boolean;validation_status:string;fingerprint:string|null;configuration:Record<string,string>;validated_at:string|null};
export function CredentialSettings(){const [statuses,setStatuses]=useState<Status[]>([]);const [alpacaKey,setAlpacaKey]=useState("");const [alpacaSecret,setAlpacaSecret]=useState("");const [routerKey,setRouterKey]=useState("");const [model,setModel]=useState("openai/gpt-4.1-mini");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);async function refresh(){setStatuses(await deskFetch<Status[]>("/desk/credentials"));}useEffect(()=>{deskFetch<Status[]>("/desk/credentials").then(setStatuses).catch((e:Error)=>setMessage(e.message));},[]);
  async function submit(event:FormEvent,provider:Provider,save:boolean){event.preventDefault();setBusy(true);setMessage("");try{const payload=provider==="alpaca"?{api_key_id:alpacaKey,secret_key:alpacaSecret}:{api_key:routerKey,model};const endpoint=`/desk/credentials/${provider}${save?"":"/test"}`;await deskFetch(endpoint,{method:save?"PUT":"POST",body:JSON.stringify(payload)});if(save){if(provider==="alpaca"){setAlpacaKey("");setAlpacaSecret("");}else setRouterKey("");await refresh();}setMessage(`${provider === "alpaca" ? "Alpaca paper" : "OpenRouter model"} ${save?"verified and encrypted":"validation passed"}.`);}catch(e){setMessage(e instanceof Error?e.message:"Validation failed");}finally{setBusy(false);}}
  async function remove(provider:Provider){setBusy(true);try{await deskFetch(`/desk/credentials/${provider}`,{method:"DELETE"});await refresh();setMessage("Credential removed and dependent access disabled.");}catch(e){setMessage(e instanceof Error?e.message:"Delete failed");}finally{setBusy(false);}}
  const alpaca=statuses.find(s=>s.provider==="ALPACA"),router=statuses.find(s=>s.provider==="OPENROUTER");return <><div className="mode-banner blue"><LockKeyhole/><div><strong>Credentials are write-only.</strong><span>Secrets are encrypted with tenant-bound AES-256-GCM and are never returned to this browser after saving.</span></div></div>{message?<p className="form-message">{message}</p>:null}<div className="settings-grid"><form className="credential-card" onSubmit={e=>submit(e,"alpaca",true)}><div className="provider-title"><KeyRound/><div><h2>Alpaca Markets</h2><p>Paper endpoint only</p></div><StatusPill status={alpaca}/></div>{alpaca?.configured?<p className="masked-record"><CheckCircle2/> Stored fingerprint: <code>{alpaca.fingerprint}</code> · {alpaca.validation_status}</p>:null}<label>Paper API key ID<input required minLength={8} autoComplete="off" value={alpacaKey} onChange={e=>setAlpacaKey(e.target.value)}/></label><label>Paper API secret<input required minLength={8} type="password" autoComplete="new-password" value={alpacaSecret} onChange={e=>setAlpacaSecret(e.target.value)}/></label><div className="button-row"><button type="button" className="secondary-button" disabled={busy||!alpacaKey||!alpacaSecret} onClick={e=>submit(e as unknown as FormEvent,"alpaca",false)}>Test paper connection</button><button disabled={busy}>Test & save encrypted</button>{alpaca?.configured?<button type="button" className="icon-button" aria-label="Delete Alpaca credentials" onClick={()=>remove("alpaca")}><Trash2/></button>:null}</div></form><form className="credential-card" onSubmit={e=>submit(e,"openrouter",true)}><div className="provider-title"><Bot/><div><h2>OpenRouter</h2><p>Read-only AI analysis</p></div><StatusPill status={router}/></div>{router?.configured?<p className="masked-record"><CheckCircle2/> Stored fingerprint: <code>{router.fingerprint}</code> · {router.configuration.model}</p>:null}<label>OpenRouter API key<input required minLength={8} type="password" autoComplete="new-password" value={routerKey} onChange={e=>setRouterKey(e.target.value)}/></label><label>Model ID<input required value={model} onChange={e=>setModel(e.target.value)} placeholder="provider/model"/></label><div className="button-row"><button type="button" className="secondary-button" disabled={busy||!routerKey||!model} onClick={e=>submit(e as unknown as FormEvent,"openrouter",false)}>Run schema probe</button><button disabled={busy}>Verify & save encrypted</button>{router?.configured?<button type="button" className="icon-button" aria-label="Delete OpenRouter credentials" onClick={()=>remove("openrouter")}><Trash2/></button>:null}</div></form></div></>}
function StatusPill({status}:{status:Status|undefined}){return <span className={status?.enabled?"status-pill good":"status-pill"}>{status?.enabled?"VERIFIED":"NOT CONNECTED"}</span>}
